---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: SilverPanda
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: etc/libvirt
        destination: /etc/libvirt/

  - type: os-release
    properties:
      ID: silver_panda
      NAME: SilverPanda
      PRETTY_NAME: SilverPanda
      
  - type: dnf
    #repos:
     # copr:
      #  - atim/starship
    install:
      packages:
      #  - micro
      #  - starship
        - fish
        - qemu
        - qemu-kvm
        - virt-manager
        - libvirt
        - virt-install
        - libvirt-daemon-config-network
        - libvirt-daemon-kvm
        - libguestfs-tools
        - util-linux
        - ptyxis
        - fastfetch
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - yelp
        - gnome-tour

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
       #   - org.mozilla.firefox
        - org.gnome.Loupe
        - org.gnome.World.PikaBackup
        - com.github.neithern.g4music
        - io.gitlab.librewolf-community
      - scope: user # Also add Flathub user repo, but no user packages
  - type: script
    scripts:
      - setup-libvirt.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
